### ISSUE TITLE
Archivo Not Finding My Tivo

### ISSUE THREAD

**Issue by sw10025** [fflewddur/archivo#113]
I just installed Archivo tonight, when it asked me about allowing the app through Windows Firewall I allowed it per the default answers, I entered my Media Access Key correctly (I think) and then tried to launch and test it.  Well, it seems to be installed correctly, and its getting to the point where it looks for my Tivo(s), but then it just sort of dies and does nothing.  All the commands are greyed out except exit, preferences, and help.

I'm using a desktop PC using Windows 10, and I do have Tivo Desktop Plus already installed, if that has any effect.  

Here is my log (which also makes me think its not finding any Tivos, even though I'm not getting an error message saying that).

00:40:56.322 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Starting up Archivo 1.1.0...
00:40:56.327 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Running on Java 1.8.0_121 from Oracle Corporation
00:40:56.327 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - System is Windows 10 (version = 10.0, arch = x86)
00:40:56.332 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume C:\ has 77268 MB free of 458983 MB
00:40:56.332 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume D:\ has 2165 MB free of 17403 MB
00:40:56.362 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume G:\ has 18461 MB free of 953867 MB
00:40:56.363 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume I:\ has 104807 MB free of 1907726 MB
00:40:56.414 [JavaFX Application Thread] INFO  n.s.archivo.model.ArchiveHistory - Loading archive history from C:\Users\Owner\AppData\Roaming\Archivo\history.xml
00:40:57.956 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
00:40:57.959 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
00:40:59.153 [pool-4-thread-1] INFO  n.s.a.controller.UpdateCheckTask - Successfully fetched update URL
00:40:59.167 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Update check: This is the latest version of Archivo (1.1.0)
00:40:59.865 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
00:41:00.068 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
00:41:00.068 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
00:41:07.293 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
00:41:07.490 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
00:41:07.490 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
00:41:14.710 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
00:41:14.926 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
00:41:14.927 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
00:41:22.139 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
00:41:22.382 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - TaskStatus cleared
01:08:31.045 [JavaFX Application Thread] INFO  n.s.archivo.model.UserPrefs - Last folder = C:\Users\Owner\Documents\My TiVo Recordings

I ran a search and found some similar instances to see if I could find a solution for my particular problem, and didn't see anything.  Here's what I've tried:  (1) Turning Tivo Desktop off; (2) conversely, tried to run Archivo while Tivo Desktop was in use, to see if it could somehow piggy back off TD somehow; (3) I saw a reference to Bonjour in one of the prior messages so I tried to turn it off and then on again within Tivo Desktop, but for some reason, that's greyed out now and I can't toggle between Bonjour and the Tivo alternative anymore (don't know if that's Archivo related or not) - but Bonjour is showing as one of my active background processes per my Task Manager; (4) I manually had my Tivo connect for programming data to see if that would kick start anything; (5) I rebooted my Tivo to see if that would kick start anything; (6) I checked my Windows Firewall app settings and while I didn't specifically see "Archivo" listed there as an approved app, I did see Java(TM) Platform SE Binary (32 bit) there, which my task manager shows Archivo as being related to, private was checked both for Java and Tivo Desktop so I checked public as well to see if that helped; and (7) I checked the Archivo preferences, and toggled between "my primary network" and the second option it gave, "Realtek PCIe GBE Family Controller (xxx.xxx.x.xx)".  Toggling between the two doesn't get different results, although one does work a lot longer before it stops trying.

Now, just now, I tried checking the second option in that category, checking the box and giving the Tivo IP address I found through the Tivo control panel (which differs ever so slightly from the number listed under Realtek on the drop down menu, and something different has happened.  Its progressed to "Fetching Recordings" but its taking an awful long time to do so.  I've got a ton of programs I downloaded on the computer and external drives through Tivo desktop, but I'm assuming its not looking at those, just looking at the 10 or 15 programs I have on the Tivo itself, and I don't think it should be hanging like this for 10 - 15 minutes or more over 15 programs or less.

Here's how the log has changed:

01:30:40.126 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Starting up Archivo 1.1.0...
01:30:40.130 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Running on Java 1.8.0_121 from Oracle Corporation
01:30:40.130 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - System is Windows 10 (version = 10.0, arch = x86)
01:30:40.135 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume C:\ has 77262 MB free of 458983 MB
01:30:40.136 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume D:\ has 2165 MB free of 17403 MB
01:30:40.165 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume G:\ has 18461 MB free of 953867 MB
01:30:40.166 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume I:\ has 104807 MB free of 1907726 MB
01:30:40.218 [JavaFX Application Thread] INFO  n.s.archivo.model.ArchiveHistory - Loading archive history from C:\Users\Owner\AppData\Roaming\Archivo\history.xml
01:30:41.998 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
01:30:42.001 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
01:30:43.805 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
01:30:44.141 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
01:30:44.141 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
01:30:45.947 [pool-4-thread-1] INFO  n.s.a.controller.UpdateCheckTask - Successfully fetched update URL
01:30:46.020 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Update check: This is the latest version of Archivo (1.1.0)
01:30:56.232 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
01:30:56.454 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
01:30:56.455 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
01:31:03.722 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
01:31:03.949 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
01:31:03.950 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
01:31:11.207 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
01:31:11.464 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - TaskStatus cleared
01:34:09.443 [JavaFX Application Thread] INFO  n.s.archivo.model.UserPrefs - Last folder = C:\Users\Owner\Documents\My TiVo Recordings
01:34:18.772 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
01:41:41.548 [JavaFX Application Thread] INFO  n.s.archivo.model.UserPrefs - Last folder = C:\Users\Owner\Documents\My TiVo Recordings
01:43:58.519 [JavaFX Application Thread] INFO  n.s.a.view.RecordingListController - New TiVo selected: Tivo[name=TiVo, tsn=unknown, addresses=[null], port=1413]
01:43:58.673 [JavaFX Application Thread] INFO  n.s.a.view.RecordingListController - New TiVo selected: Tivo[name=TiVo, tsn=unknown, addresses=[/192.168.0.13], port=1413]
01:43:58.674 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Fetching recordings...'
01:44:20.248 [pool-2-thread-1] ERROR n.s.archivo.net.MindTask - Error executing MindTask: 
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.<init>(Unknown Source)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(Unknown Source)
	at net.straylightlabs.archivo.net.MindRPC.connect(MindRPC.java:98)
	at net.straylightlabs.archivo.net.MindRPC.connectAndAuthenticate(MindRPC.java:92)
	at net.straylightlabs.archivo.net.MindRPC.send(MindRPC.java:143)
	at net.straylightlabs.archivo.net.MindCommand.execute(MindCommand.java:81)
	at net.straylightlabs.archivo.net.MindCommand.executeOn(MindCommand.java:89)
	at net.straylightlabs.archivo.net.MindTask.call(MindTask.java:42)
	at net.straylightlabs.archivo.net.MindTask.call(MindTask.java:28)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
01:44:20.290 [JavaFX Application Thread] ERROR n.s.a.view.RecordingListController - Error fetching recordings from TiVo: 
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.<init>(Unknown Source)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(Unknown Source)
	at net.straylightlabs.archivo.net.MindRPC.connect(MindRPC.java:98)
	at net.straylightlabs.archivo.net.MindRPC.connectAndAuthenticate(MindRPC.java:92)
	at net.straylightlabs.archivo.net.MindRPC.send(MindRPC.java:143)
	at net.straylightlabs.archivo.net.MindCommand.execute(MindCommand.java:81)
	at net.straylightlabs.archivo.net.MindCommand.executeOn(MindCommand.java:89)
	at net.straylightlabs.archivo.net.MindTask.call(MindTask.java:42)
	at net.straylightlabs.archivo.net.MindTask.call(MindTask.java:28)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Anyone have any suggestions about what I've done wrong or what I need to do to fix this?  I'd like to have this working as a back up next time Tivo Desktop is acting up, or since I'm told its no longer supported, it stops working altogether.  Thanks in advance.

**Comment by fflewddur** [comment]
Hmm, that second log suggests that even when you put in the IP address for the TiVo, Archivo still couldn't connect to it. But if TiVo Desktop has been able to connect to it, I'm assuming everything on your network is fine. What model of TiVo are you trying to connect to?

**Comment by sw10025** [comment]
Its an old Tivo Series 2.

**Comment by fflewddur** [comment]
Ah, Archivo only support Series 4 devices and newer.

**Comment by sw10025** [comment]
Ah OK, that's too bad.  Oh well. But thank you for letting me know. No chance of my upgrading at present.
