### ISSUE TITLE
failed to download

### ISSUE THREAD

**Issue by mikereallyoldguy** [fflewddur/archivo#127]
I have a number of video files I uploaded to my Tivo. They all play on Tivo. When I tried to download them to archivo only about half of them would download the others produce a fail to download error. Here is the log file extract cover a file download that failed.
10:13:54.662 [pool-3-thread-2] ERROR n.s.archivo.controller.ArchiveTask - Failed to download file (14588344 bytes read, 20971520 bytes expected)
10:13:54.665 [JavaFX Application Thread] ERROR n.s.a.c.ArchiveQueueManager - ArchiveTask failed for anna and the camera: 
net.straylightlabs.archivo.controller.ArchiveTaskException: Failed to download recording
	at net.straylightlabs.archivo.controller.ArchiveTask.verifyDownloadSize(ArchiveTask.java:388)
	at net.straylightlabs.archivo.controller.ArchiveTask.handleResponse(ArchiveTask.java:337)
	at net.straylightlabs.archivo.controller.ArchiveTask.getRecording(ArchiveTask.java:235)
	at net.straylightlabs.archivo.controller.ArchiveTask.archive(ArchiveTask.java:139)
	at net.straylightlabs.archivo.controller.ArchiveTask.call(ArchiveTask.java:106)
	at net.straylightlabs.archivo.controller.ArchiveTask.call(ArchiveTask.java:59)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
10:13:54.668 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - TaskStatus cleared

**Comment by github-geek** [comment]
For me Archivo quit completely..   I also have Tivo Desktop Plus which has stopped working.   When I contacted TiVo support they told me that Tivo Desktop is no longer supported with the new "Experience 4" software (on my Roamio) and that if I want to use it I need to downgrade to "Experience 3" software, which in turn, will delete all my shows.   I suspect this lack of support for transferring in Experience 4 has killed the functionality of Archivo.    
Can the moderator/developer please confirm or deny?   

Is Archivo a dead app?

**Comment by mikereallyoldguy** [comment]
Mine works just fine, I wish I could remember where but I had to download a special file to fix the archivo download problem, do what I did and Google the archivo problem. I am on experience 4. My desktop plus works. I got the same response from TiVo as you did but there is a workaround from a kindly or knowledgeable TiVo tech.1 do three forced connections to TiVo with restart after each.2 power down TiVo, router.2a power down and UNPLUG power cord on target pc3 power up router4 power up TiVo5 power up PC you may have to do this several times until desktop plus sees the TiVo.I think network discovery needs a little time to allow PC to see TiVo. Once connected desktop plus will work until next TiVo restart. Good luckI prefer archivo. Will look for the needed file. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: github-geek <notifications@github.com> Date: 7/30/20  11:25 AM  (GMT-06:00) To: fflewddur/archivo <archivo@noreply.github.com> Cc: mikereallyoldguy <mjbartn@charter.net>, Author <author@noreply.github.com> Subject: Re: [fflewddur/archivo] failed to download (#127) 
For me Archivo quit completely..   I also have Tivo Desktop Plus which has stopped working.   When I contacted TiVo support they told me that Tivo Desktop is no longer supported with the new "Experience 4" software (on my Roamio) and that if I want to use it I need to downgrade to "Experience 3" software, which in turn, will delete all my shows.   I suspect this lack of support for transferring in Experience 4 has killed the functionality of Archivo.
Can the moderator/developer please confirm or deny?
Is Archivo a dead app?

**Comment by mikereallyoldguy** [comment]
Here is the java file fix for the current archivo. Google it first to understand what is going on 

JavaSetup8u251 exe, I removed period before exe.

 

Good luck

**Comment by github-geek** [comment]
Thanks for the input..   I installed the Java update and by itself, did not help.  I haven't gone through the gyrations you described for reboots, forced connects, etc..  just yet.   
Can you link your Tivo Desktop Plus to your Tivo acct?   Mine won't even do that.. it fails to link.  and without the linking you can't use it to pull shows off the tivo.   Archivo still spins looking for Tivos on the network and then silently just stops. 
My log.txt on Archivo looks like this,  which shows it's using Java 1.8.0_261 and not the newly installed update 251..   do I need to uninstall Java then install the 251 vers?

12:22:57.612 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Starting up Archivo 1.1.0...
12:22:57.616 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Running on Java 1.8.0_261 from Oracle Corporation
12:22:57.617 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - System is Windows 10 (version = 10.0, arch = x86)
12:22:57.622 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume C:\ has 482686 MB free of 951488 MB
12:22:57.623 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume D:\ has 939431 MB free of 953867 MB
12:22:57.710 [JavaFX Application Thread] INFO  n.s.archivo.model.ArchiveHistory - Loading archive history from C:\Users\xyzzy\AppData\Roaming\Archivo\history.xml
12:22:59.858 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
12:22:59.860 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
12:23:01.039 [pool-4-thread-1] INFO  n.s.a.controller.UpdateCheckTask - Successfully fetched update URL
12:23:01.042 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Update check: This is the latest version of Archivo (1.1.0)
12:23:01.774 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
12:23:02.202 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
12:23:02.203 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
12:23:10.047 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
12:23:10.471 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
12:23:10.471 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
12:23:18.251 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
12:23:18.641 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
12:23:18.642 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
12:23:26.430 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
12:23:27.018 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - TaskStatus cleared
12:24:09.338 [JavaFX Application Thread] INFO  n.s.archivo.model.UserPrefs - Last folder = D:\TV Shows\TiVo

**Comment by github-geek** [comment]
WHOA!!!!  I just killed Archivo and restarted it and it pulled up my shows!!!
started a transfer now..  let's see it works!

**Comment by github-geek** [comment]
Do you know if there are any dependencies on Tivo Desktop for Archivo to function?  Can I uninstall TiVo Desktop Plus without impacting Archivo?

**Comment by mikereallyoldguy** [comment]
I think I completely uninstalled archivo using ccleaner free. Do a Google search on the Java and archivo problem. As for TiVo not sure what you mean link to the account. You do need your TiVo key.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: github-geek <notifications@github.com> Date: 7/30/20  2:35 PM  (GMT-06:00) To: fflewddur/archivo <archivo@noreply.github.com> Cc: mikereallyoldguy <mjbartn@charter.net>, Author <author@noreply.github.com> Subject: Re: [fflewddur/archivo] failed to download (#127) 
Thanks for the input..   I installed the Java update and by itself, did not help.  I haven't gone through the gyrations you described for reboots, forced connects, etc..  just yet.
Can you link your Tivo Desktop Plus to your Tivo acct?   Mine won't even do that.. it fails to link.  and without the linking you can't use it to pull shows off the tivo.   Archivo still spins looking for Tivos on the network and then silently just stops.
My log.txt on Archivo looks like this,  which shows it's using Java 1.8.0_261 and not the newly installed update 251..   do I need to uninstall Java then install the 251 vers?
12:22:57.612 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Starting up Archivo 1.1.0...
12:22:57.616 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Running on Java 1.8.0_261 from Oracle Corporation
12:22:57.617 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - System is Windows 10 (version = 10.0, arch = x86)
12:22:57.622 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume C:\ has 482686 MB free of 951488 MB
12:22:57.623 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Volume D:\ has 939431 MB free of 953867 MB
12:22:57.710 [JavaFX Application Thread] INFO  n.s.archivo.model.ArchiveHistory - Loading archive history from C:\Users\xyzzy\AppData\Roaming\Archivo\history.xml
12:22:59.858 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
12:22:59.860 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
12:23:01.039 [pool-4-thread-1] INFO  n.s.a.controller.UpdateCheckTask - Successfully fetched update URL
12:23:01.042 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Update check: This is the latest version of Archivo (1.1.0)
12:23:01.774 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
12:23:02.202 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
12:23:02.203 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
12:23:10.047 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
12:23:10.471 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
12:23:10.471 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
12:23:18.251 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
12:23:18.641 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
12:23:18.642 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
12:23:26.430 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
12:23:27.018 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - TaskStatus cleared
12:24:09.338 [JavaFX Application Thread] INFO  n.s.archivo.model.UserPrefs - Last folder = D:\TV Shows\TiVo

**Comment by mikereallyoldguy** [comment]
That's goodSent from my Samsung Galaxy smartphone.
-------- Original message --------From: github-geek <notifications@github.com> Date: 7/30/20  2:36 PM  (GMT-06:00) To: fflewddur/archivo <archivo@noreply.github.com> Cc: mikereallyoldguy <mjbartn@charter.net>, Author <author@noreply.github.com> Subject: Re: [fflewddur/archivo] failed to download (#127) 
WHOA!!!!  I just killed Archivo and restarted it and it pulled up my shows!!!
started a transfer now..  let's see it works!

**Comment by mikereallyoldguy** [comment]
Not sureSent from my Samsung Galaxy smartphone.
-------- Original message --------From: github-geek <notifications@github.com> Date: 7/30/20  2:45 PM  (GMT-06:00) To: fflewddur/archivo <archivo@noreply.github.com> Cc: mikereallyoldguy <mjbartn@charter.net>, Author <author@noreply.github.com> Subject: Re: [fflewddur/archivo] failed to download (#127) 
Do you know if there are any dependencies on Tivo Desktop for Archivo to function?  Can I uninstall TiVo Desktop Plus without impacting Archivo?
