### ISSUE TITLE
Looking for Tivos

### ISSUE THREAD

**Issue by aspexil-alex** [fflewddur/archivo#46]
Mac OS X 10.10.5

Put my MAK # in and the spinner stays on Looking for Tivos...

Any thoughts what I should try next?

**Comment by fflewddur** [comment]
Thanks for the bug report. I've been trying to replicate this by trying different Java security settings and user/administrative privileges on my Mac, but I can't seem to do so. My guess is that somehow, your system is configured to prevent Java from accessing a network socket in multicast mode (hence the permission denied error when it tries to write to that socket). My testing has been on a Macbook with 10.11.1 and Oracle Java 1.8.0_66; I've tried both standard and administrative user accounts, and set my Java security settings to High and Very High, but Archivo can still find my TiVo correctly. It may be worth playing around with some of those settings yourself to see if they make a difference. Firewall settings may be something else to try. I'll keeping looking into this, but for the moment, I'm not sure what the issue is.

**Comment by aspexil-alex** [comment]
Hi, I thought it was a strange error.  BTW I work for IBM on WebSphere so
fairly Java savvy and also thought it was firewall or security related but
no changes fixed it.  I'll hit up some of my Java developers (they actually
work on IBM's Java) and see what they think.

I'll see what other Mac apps use multicast mode and see if any correlation.
BTW I also run a Plex server on this mac.  -Alex

**Comment by fflewddur** [comment]
Thanks Alex! I'm wondering if the Plex server, or something else listening on the mDNS port, might be the issue. Archivo uses the SO_REUSEPORT socket option to allow other processes to share the mDNS socket, but if another process opens that socket (before Archivo) without that option, then Archivo won't be able to access it. You can test this hypothesis by shutting down anything listening on UDP port 5353 (except for Apple's mDNSResponder service, that one definitely plays nice with Archivo) and then starting Archivo again.

**Comment by stevehoek** [comment]
I have a similar issue on a Mac with latest OS and Java 
One of the tech previews worked, but beta1 does not:

11:23:31.567 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
11:23:31.598 [pool-2-thread-1] ERROR n.s.archivo.net.TivoSearchTask - Error searching for TiVo devices: 
java.io.IOException: No route to host
	at java.net.PlainDatagramSocketImpl.send(Native Method) ~[na:1.8.0_66]
	at java.net.DatagramSocket.send(DatagramSocket.java:693) ~[na:1.8.0_66]
	at net.straylightlabs.hola.dns.Question.askWithGroup(Question.java:114) ~[hola-0.1.2.jar:na]
	at net.straylightlabs.hola.dns.Question.askOn(Question.java:105) ~[hola-0.1.2.jar:na]
	at net.straylightlabs.hola.sd.Query.runOnce(Query.java:84) ~[hola-0.1.2.jar:na]
	at net.straylightlabs.archivo.net.TivoSearchTask.startSearch(TivoSearchTask.java:68) [Archivo.jar:na]
	at net.straylightlabs.archivo.net.TivoSearchTask.call(TivoSearchTask.java:59) [Archivo.jar:na]
	at net.straylightlabs.archivo.net.TivoSearchTask.call(TivoSearchTask.java:41) [Archivo.jar:na]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) [jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

**Comment by fflewddur** [comment]
@aspexil-alex and @stevehoek : Can either of you let me know if Archivo 1.0.1 is still failing to find your TiVos? You can find the latest release at http://straylightlabs.net/archivo/#download. Thanks!

**Comment by stevehoek** [comment]
I have 2 Mac's and 1 Windows machine here.
The 2 Mac's could not access either of my 2 TiVo's.  I tried with Archivo
1.0 and 1.0.1
The Windows machine could with 1.0, but cannot with 1.0.1

Here is the log from the Windows machine.  It looks to be getting hung up
on my physical and virtual optical drives (X and V respectively)


23:24:09.186 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Starting up Archivo 1.0.1...
23:24:09.191 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Running on Java 1.8.0_77 from Oracle
Corporation
23:24:09.191 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - System is Windows Server 2008 R2
(version = 6.1, arch = amd64)
23:24:09.200 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Volume B:\ has 14732717 MB free of
22773561 MB
23:24:09.201 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Volume C:\ has 54212 MB free of
171569 MB
23:24:09.205 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Volume D:\ has 14732717 MB free of
22773561 MB
23:24:09.210 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Volume M:\ has 14732717 MB free of
22773561 MB
23:24:09.215 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Volume P:\ has 14732717 MB free of
22773561 MB
23:24:09.217 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Volume Q:\ has 21034084 MB free of
60706113 MB
23:24:09.222 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Volume S:\ has 14732717 MB free of
22773561 MB
23:24:09.227 [JavaFX Application Thread] ERROR
net.straylightlabs.archivo.Archivo - Error getting available disk space for
volume V:\:
java.nio.file.FileSystemException: V:\: The device is not ready.

at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
~[na:1.8.0_77]
at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
~[na:1.8.0_77]
at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
~[na:1.8.0_77]
at sun.nio.fs.WindowsLinkSupport.getFinalPath(Unknown Source) ~[na:1.8.0_77]
at sun.nio.fs.WindowsFileStore.create(Unknown Source) ~[na:1.8.0_77]
at sun.nio.fs.WindowsFileSystemProvider.getFileStore(Unknown Source)
~[na:1.8.0_77]
at java.nio.file.Files.getFileStore(Unknown Source) ~[na:1.8.0_77]
at net.straylightlabs.archivo.Archivo.logVMInfo(Archivo.java:145)
[Archivo.jar:na]
at net.straylightlabs.archivo.Archivo.start(Archivo.java:99)
[Archivo.jar:na]
at
com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(Unknown
Source) [jfxrt.jar:na]
at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(Unknown
Source) ~[jfxrt.jar:na]
at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)
~[jfxrt.jar:na]
at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_77]
at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown
Source) ~[jfxrt.jar:na]
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
~[jfxrt.jar:na]
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
~[jfxrt.jar:na]
at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
~[jfxrt.jar:na]
at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_77]
23:24:09.245 [JavaFX Application Thread] ERROR
net.straylightlabs.archivo.Archivo - Error getting available disk space for
volume X:\:
java.nio.file.FileSystemException: X:\: The device is not ready.

at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
~[na:1.8.0_77]
at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
~[na:1.8.0_77]
at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
~[na:1.8.0_77]
at sun.nio.fs.WindowsLinkSupport.getFinalPath(Unknown Source) ~[na:1.8.0_77]
at sun.nio.fs.WindowsFileStore.create(Unknown Source) ~[na:1.8.0_77]
at sun.nio.fs.WindowsFileSystemProvider.getFileStore(Unknown Source)
~[na:1.8.0_77]
at java.nio.file.Files.getFileStore(Unknown Source) ~[na:1.8.0_77]
at net.straylightlabs.archivo.Archivo.logVMInfo(Archivo.java:145)
[Archivo.jar:na]
at net.straylightlabs.archivo.Archivo.start(Archivo.java:99)
[Archivo.jar:na]
at
com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(Unknown
Source) [jfxrt.jar:na]
at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(Unknown
Source) ~[jfxrt.jar:na]
at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)
~[jfxrt.jar:na]
at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_77]
at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown
Source) ~[jfxrt.jar:na]
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
~[jfxrt.jar:na]
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
~[jfxrt.jar:na]
at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
~[jfxrt.jar:na]
at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_77]
23:24:09.246 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Volume Y:\ has 10572178 MB free of
11443960 MB
23:24:09.247 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Volume Z:\ has 11314404 MB free of
11443960 MB
23:24:09.249 [JavaFX Application Thread] INFO
 n.s.archivo.model.ArchiveHistory - Loading archive history from
C:\Users\Steve Hoek\AppData\Roaming\Archivo\history.xml
23:24:10.103 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Setting status to 'Looking for
TiVos...'
23:24:10.107 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask -
Starting search for TiVo devices...
23:24:10.868 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found
instances: []
23:24:10.879 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - TaskStatus cleared
23:24:11.171 [pool-4-thread-1] INFO  n.s.a.controller.UpdateCheckTask -
Successfully fetched current_version.xml
23:24:11.195 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Update check: This is the latest
version of Archivo (1.0.1)
23:24:12.528 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Setting status to 'Looking for
TiVos...'
23:24:12.529 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask -
Starting search for TiVo devices...
23:24:17.530 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found
instances: []
23:24:17.530 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - TaskStatus cleared

**Comment by stevehoek** [comment]
Here is the log from one of the Macs

23:29:13.072 [JavaFX Application Thread] INFO  n.s.archivo.model.UserPrefs
- Tools in '/Applications/Archivo.app/Contents/MacOS'
23:29:13.077 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Starting up Archivo 1.0.1...
23:29:13.077 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Running on Java 1.8.0_77 from Oracle
Corporation
23:29:13.077 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - System is Mac OS X (version =
10.11.4, arch = x86_64)
23:29:13.083 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Volume / has 405277 MB free of 953030
MB
23:29:13.087 [JavaFX Application Thread] INFO
 n.s.archivo.model.ArchiveHistory - Loading archive history from
/Users/shoek/Library/Application Support/Archivo/history.xml
23:29:14.011 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Setting status to 'Looking for
TiVos...'
23:29:14.013 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask -
Starting search for TiVo devices...
23:29:14.033 [pool-2-thread-1] ERROR n.s.archivo.net.TivoSearchTask - Error
searching for TiVo devices:
java.io.IOException: No route to host
at java.net.PlainDatagramSocketImpl.send(Native Method) ~[na:1.8.0_77]
at java.net.DatagramSocket.send(DatagramSocket.java:693) ~[na:1.8.0_77]
at net.straylightlabs.hola.dns.Question.askWithGroup(Question.java:114)
~[hola-0.1.3.jar:na]
at net.straylightlabs.hola.dns.Question.askOn(Question.java:105)
~[hola-0.1.3.jar:na]
at net.straylightlabs.hola.sd.Query.runOnce(Query.java:91)
~[hola-0.1.3.jar:na]
at
net.straylightlabs.archivo.net.TivoSearchTask.startSearch(TivoSearchTask.java:78)
[Archivo.jar:na]
at
net.straylightlabs.archivo.net.TivoSearchTask.call(TivoSearchTask.java:65)
[Archivo.jar:na]
at
net.straylightlabs.archivo.net.TivoSearchTask.call(TivoSearchTask.java:41)
[Archivo.jar:na]
at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) [jfxrt.jar:na]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_77]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[na:1.8.0_77]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_77]
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[na:1.8.0_77]
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[na:1.8.0_77]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
23:29:14.300 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - TaskStatus cleared
23:29:14.495 [pool-4-thread-1] INFO  n.s.a.controller.UpdateCheckTask -
Successfully fetched current_version.xml
23:29:14.527 [JavaFX Application Thread] INFO
 net.straylightlabs.archivo.Archivo - Update check: This is the latest
version of Archivo (1.0.1)

**Comment by aspexil-alex** [comment]
I'm away on business but will try this weekend.

---
From my mobile Nexus 6

**Comment by fflewddur** [comment]
Thanks @stevehoek! That's odd that 1.0 worked but 1.0.1 doesn't; nothing changed in the networking code between the releases, so in your case, this issue *might* indicate a multicast problem on your local network. That fact that this happens intermittently from three different machines also suggests a network issue. Can you describe how your computers and your TiVos are networked together?

The log file exceptions about your optical drives are normal if the drive is empty; I should squash those to keep them out of the logs, but they don't indicate that anything's wrong.

**Comment by stevehoek** [comment]
Network here is pretty standard (PC's and TiVo's connected to the same
switch).  It does not happen intermittently.  None of my 3 Archivo installs
can see my Tivos anymore now that I am on 1.0.1.
Thanks for looking into it!

**Comment by fflewddur** [comment]
Alright, thanks for the update! I'll keep looking into what might be causing this... you're not alone, but I haven't been able to reproduce this problem on my own network (yet).

**Comment by fflewddur** [comment]
I think I finally have a fix for this. Could you try downloading the attached hola-0.1.3.jar.zip file, unzip it, and replace the hola-0.1.3.jar file in C:\Program Files (x86)\Archivo with it? On a Mac, you'll need to right-click /Applications/Archivo, select "Show Package Contents", and navigate to Contents->Java to find the place to paste this file. Let me know if it helps.
[hola-0.1.3.jar.zip](https://github.com/fflewddur/archivo/files/229222/hola-0.1.3.jar.zip)

**Comment by stevehoek** [comment]
Thanks Todd.
This works on my PC, but not my Mac.

**Comment by fflewddur** [comment]
Thanks Steve, I found a problem with my Mac detecting TiVos this past weekend and fixed it, hopefully it's the same issue you're seeing. I should have some time to roll a new Archivo release this weekend to improve the reliability of TiVo discovery.

**Comment by fflewddur** [comment]
... and the new release is available at https://github.com/fflewddur/archivo/releases/tag/v1.0.2. Can you let me know if this resolves the problem?

**Comment by stevehoek** [comment]
Hi,
I tried 1.0.2 on m PC and it could not find any TiVo's (but 1.0.1 with your
patched hola-0.1.3.jar worked)

I tried 1.0.3 on my Mac and it could not find any TiVo's and had this error
in the log

17:20:51.673 [pool-2-thread-1] ERROR net.straylightlabs.hola.sd.Query -
SocketException when joining group for FF02::FB, IPv6-only hosts will not
be found
java.net.SocketException: Invalid argument
at java.net.PlainDatagramSocketImpl.join(Native Method)
at
java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
at net.straylightlabs.hola.sd.Query.openSocket(Query.java:136)
at net.straylightlabs.hola.sd.Query.runOnce(Query.java:102)
at
net.straylightlabs.archivo.net.TivoSearchTask.startSearch(TivoSearchTask.java:79)
at
net.straylightlabs.archivo.net.TivoSearchTask.call(TivoSearchTask.java:66)
at
net.straylightlabs.archivo.net.TivoSearchTask.call(TivoSearchTask.java:41)
at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

**Comment by stevehoek** [comment]
Jut a quick note.. 1.0.3 DOES work on my Windows PC again.

Thx!

**Comment by fflewddur** [comment]
@stevehoek I just released 1.0.4, which should find TiVos reliably on Mac OS X. The one exception I've noticed is that if VMware is running, it won't work; this appears to be an issue with Java itself, which tries to use the VMware network interface instead of the Mac's.

**Comment by aspexil-alex** [comment]
Sorry I've been busy on business travel. I'll try this out later this week
and see if it clears up the issue on my end. -Alex

**Comment by fflewddur** [comment]
@aspexil-alex and @stevehoek : I just released Archivo 1.1, which allows you to specify the network Archivo to use when searching for TiVos, or manually specify the IP address of your TiVo. Does this this resolve the problem for you? The new version is available at https://straylightlabs.net/archivo/#download.

**Comment by aspexil-alex** [comment]
I'm travelling on business but will give this a shot later. Thanks, -Alex

**Comment by stevehoek** [comment]
This latest version solved all the problems for me on both Windows and Mac.
Thanks!

I like the new preference for network specification... I have 2 other
networks (one for VPN, another for VM), and it must have been confusing
things for Archivo.  I do notice that if I try to select "en1" it does not
reflect it as selected in the combobox right away, or after a restart.  I
don't need to select the network, however, since Archivo is finding the
right one from the start.

**Comment by aspexil-alex** [comment]
So I'm just catching up here now. Archivo 1.1.0 does not start for me on my
Mac. Here is my java version

~ $ java -version

java version "1.8.0_71"

Java(TM) SE Runtime Environment (build 1.8.0_71-b15)

Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)

[alexandrepolozoff@Alexandres-MacBook-Air ~] 2016-08-25 12:43:38
